### ISSUE TITLE
On client after clicking on sync status it is showing the error on production 8.0 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1396] opened 2024-05-10 09:15 UTC
**Describe the bug**
On client after clicking on sync status it is showing the error
I created a one work order with  name TRISHA which contains  one image and one video 
then I try to sync it.. it will sync successfully but showing me this error

**To Reproduce**
1. Login with AchalaB@rwbnitiuat
2. create on subject type sync it
3. see on sync status.

https://github.com/avniproject/avni-client/assets/104890488/f6d4bb79-cc86-4af7-9244-373b274f7f5d

### Analysis:
- The db is uploaded
- env is avni prod - open testing track

**Comment by himeshr** [comment] 2024-05-13 09:31
Updated documentation related to Sync internals with info about this use-case.
https://avni.readme.io/docs/internal-details-of-avni-sync#sync-specific-data-storage

**Comment by himeshr** [comment] 2024-05-13 09:34
After dicussion with Maha, concluded that this is currently working as designed and we would not need to fix it on priority.
Putting on hold, to allow for further discussion about if and how this issue has to be fixed in code.

**Comment by himeshr** [comment] 2024-05-13 09:40
Debug info:
-----------
On the device, some media entries that were selected for ENcounter observations were deleted.
Due to this, the MediaUploadService was highlighting those as seen in the card description.
This is as per current design, with intention to alert the User about error with the synced entities missing media content.


--------------------
Error entries in the Media Queue:

<img width="1796" alt="Screenshot 2024-05-13 at 2 23 21 PM" src="https://github.com/avniproject/avni-client/assets/72493481/e4590f47-b649-49e9-b1ad-81a581a55a75">


--------------------
Encounter observations which has no S3 unsigned URLs, but was synced successfully to the server:

<img width="1840" alt="Screenshot 2024-05-13 at 2 22 50 PM" src="https://github.com/avniproject/avni-client/assets/72493481/647ed684-74ae-4fee-b6a9-6e5c03228eec">

**Comment by himeshr** [comment] 2024-05-20 05:35
@mahalakshme as discussed earlier, this looks to be working as designed.
As this is not breaking any functionality, i think we should close this card.

**Closed as completed by himeshr** 2024-05-20 05:35 UTC
