### ISSUE TITLE
Voided ID type field still gives error due to missing entries in identifier assignment tables

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#1064] opened 2023-08-03 11:22 UTC
**Describe the bug**
In one of the implementation, Unique identifiers were used in one of the subject registration, but later it was removed from the form. When new users were created without assigning identifiers to them, the app still gave error while user tried to register that subject.

**To Reproduce**
1. Go to APF Odisha organisation
2. Create a new Poshan Sathi user (add to respective user group and sync attributes)
3. Sync the mobile app and try to Register a new Household subject type

**Expected behavior**
Ideally, when an identifier source is voided, client should not look for any kind of user assignment and work fine for all the users.

**Screenshots**

![Image](https://github.com/avniproject/avni-client/assets/37863085/32e62d54-3a42-4a02-831d-07a14e8b0198)

**Additional context**
This is important as it is causing issues on ground for APF whenever they create a new user.

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by himeshr** [comment] 2023-08-03 11:57
Duplicate of #1063

**Comment by petmongrels** [comment] 2023-08-03 11:59
We have to discuss whether voiding of identifier source should be used as information or should the form element of id type be expected to be voided too (which has been done in #1063)

**Comment by arjunk** [comment] 2023-08-03 12:08
> We have to discuss whether voiding of identifier source should be used as information or should the form element of id type be expected to be voided too (which has been done in #1063)

Voiding of identifier source and voiding of form element of id type are two different activities use-case wise. In the current scenario what's happening is the when trying to process

**Comment by vinayvenu** [comment] 2023-08-03 12:44
@arjunk I don't understand this scenario. We only look for presence of identifiers when a form element in the form you are going to fill requires it. 

What is the scenario where there is a form element with a concept marked to a specific id source in a form, but the id source is voided?

**Comment by vinayvenu** [comment] 2023-08-09 09:06
Closing this ticket as duplicate.

**Closed as completed by vinayvenu** 2023-08-09 09:06 UTC
Labels: bug, user reported
