### ISSUE TITLE
Unable to see the new form in Metabase

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1199] opened 2023-11-22 06:33 UTC
https://avni.freshdesk.com/a/tickets/3236

- Suggest a temporary fix
- Also see how this can be fixed at ETL level or at a product level(if it needs to be fixed) to prevent occurrence of similar issue.

**Comment by 1t5j0y** [comment] 2023-11-27 05:02
Unclear what the issue is as the table is available in etl (and metabase to query) with the columns from the form currently linked.

**Comment by 1t5j0y** [comment] 2023-12-05 04:18
Corresponding ticket is closed in freshdesk. Closing this card as well.

**Closed as completed by 1t5j0y** 2023-12-05 04:18 UTC
