### ISSUE TITLE
Completed general encounter is not showing in UI

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#980] opened 2023-05-25 06:23 UTC
**Describe the bug**
First time when an unplanned general encounter is getting completed, the completed visit doesn't show up in the UI/completes encounters section in General tab. While on second time, when the same type of visit is completed second time it does show it on UI. Also, observations from the first completed visit are not available in the next planned visits (in the rule) though the visit is getting stored in DB.

**To Reproduce**
1. Go to STCATP UAT org mobile app
2. Click on any individual
3. Go to General tab (case when no general encounter is done)
4. Start with completing the "Start SS Facilitation Schemes" visit, and save it
3. Scroll down to Completed encounters
4. See that the completed visit is not shown and also in the next scheduled encounter no data from first visit is available

**Screenshots**
https://images.zenhubusercontent.com/64590403/00b77df5-7681-452c-9678-08ef1548174d/whatsapp_video_2023_05_25_at_11_53_17.mp4

**Comment by vinayvenu** [comment] 2023-05-25 11:41
@nupoorkhandelwal are you able to reproduce this issue?

**Comment by nupoorkhandelwal** [comment] 2023-05-29 13:53
@vinayvenu yes, the video is recorded by me and also demoed this to @mahalakshme already.

**Comment by vinayvenu** [comment] 2023-05-30 03:47
@nupoorkhandelwal ok. In that case, I believe @mahalakshme can work on this one. I could not reproduce the issue on a regular organisation. Moving to 3.40 release.

**Comment by mahalakshme** [comment] 2023-05-30 05:11
@vinayvenu I didnt try to reproduce the issue. but was unable to see how implementation changes could have caused the issue. So felt someone need to analyse/debug the code to find out why the issue is happening. so have moved the card to In Analysis and assigned myself

**Comment by mahalakshme** [comment] 2023-05-30 08:56
@nupoorkhandelwal @vinayvenu with 3.39 release this will get fixed. Fixed as part of this issue: https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-client/960

**Closed as completed** 2023-06-20 06:48 UTC
Labels: bug
