### ISSUE TITLE
[avni-client] Sequence of fields in summary of the form is different from the actual sequence in the form

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#437] opened 2021-02-19 16:12 UTC
**Describe the bug**
In the avni mobile app, for each form there is an option to view the complete summary when the form is filled.Ideally the sequence of fields in the summary should be same , ie. they should be in same order as displayed in the form and screens respectively.

**To Reproduce**
1. Go to avni app
2. Click on option to view the summary of any form (enrolment/encounter)
3. Scroll down and check, the fields are randomly displayed (different order from the order of fields in the actual form)
4. So this is the issue.

**Screenshots**

**Comment by vindeolal** [comment] 2021-03-05 12:49
@nupoorkhandelwal 

I'm not able to reproduce it. As suggested tried on pregnancy enrollment on Chetna Sneha, could not see any obs in wrong order on the client. Please provide more details to reproduce it correctly.
I used below script to see the obs in correct order on client.
```
select c.name, feg.display_order, fe.display_order
from form_element fe
         join concept c on fe.concept_id = c.id
         join form_element_group feg on fe.form_element_group_id = feg.id
         join form f on feg.form_id = f.id
where f.name = 'Pregnant Woman Enrolment'
and fe.is_voided = false
and feg.is_voided = false
order by feg.display_order, fe.display_order
```
Moving it back

**Closed as completed** 2021-03-05 13:13 UTC
Labels: bug

**Comment by nupoorkhandelwal** [comment] 2021-03-05 13:15
Implementation Chetna-Sneha had reported this, but we checked and the sequence is proper. Only the voided elements show up in the last, which is causing confusion. Will inform them accordingly.
