### ISSUE TITLE
[PoWER UAT] Unable to deselect a checkbox in Task Filter page

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#818] opened 2023-01-25 09:04 UTC
- [x]  Unable to deselect  the multi select check button 

[https://app.zenhub.com/files/64590403/6eb4af56-ffca-4dd2-8692-46bc3377d0d5/download](https://app.zenhub.com/files/64590403/6eb4af56-ffca-4dd2-8692-46bc3377d0d5/download)

 ̶-̶ ̶[̶ ̶]̶ ̶U̶n̶a̶b̶l̶e̶ ̶t̶o̶ ̶c̶l̶o̶s̶e̶ ̶t̶h̶e̶ ̶o̶p̶e̶n̶ ̶t̶a̶s̶k̶ ̶p̶a̶g̶e̶ ̶w̶h̶e̶n̶ ̶I̶ ̶a̶m̶ ̶t̶r̶y̶i̶n̶g̶ ̶t̶o̶ ̶c̶l̶i̶c̶k̶ ̶o̶n̶ ̶C̶r̶o̶s̶s̶ ̶i̶c̶o̶n̶.̶ ̶I̶t̶ ̶i̶s̶ ̶n̶o̶t̶ ̶r̶e̶s̶p̶o̶n̶d̶i̶n̶g̶ ̶.̶

[https://app.zenhub.com/files/64590403/d49e1057-3191-4856-91b6-e4dd60e90e16/download](https://app.zenhub.com/files/64590403/d49e1057-3191-4856-91b6-e4dd60e90e16/download)

Note: Above entry has been removed as per explanation given in one of the comments below _"the cross button is for clearing filters selected on the task list screen and not to close the task-list screen."_

**Comment by himeshr** [comment] 2023-01-25 09:33
On discussion with Vinay, figured out that the second issue raised as part of this card is not a bug. Its working as designed.
"Unable to close the open task page when I am trying to click on Cross icon. It is not responding .", the cross button is for clearing filters selected on the task list screen and not to close the task-list screen.

**Comment by vinayvenu** [comment] 2023-01-30 06:32
Closing this card based on comments by @himeshr

**Closed as completed by vinayvenu** 2023-01-30 06:32 UTC

**Comment by himeshr** [comment] 2023-01-30 06:53
Additionally,  the issue "Unable to deselect the multi select check button" is now working in the latest version of the avni-client.
