### ISSUE TITLE
App is crashing after clicking on individual of  type student 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1110] opened 2023-09-26 08:11 UTC
**Describe the bug**
After login select subject type student
Click on any student
Login Id : utkarsh@lahi

**To Reproduce**
1.login with utkarsh@lahi 
2. click n search 
3. click on student subject type
4.  click on any student

**Expected behavior**
user is able to see the student details

**Screenshots**

https://github.com/avniproject/avni-client/assets/104890488/17e0c5c3-83ed-486e-83cb-98f32320d560

**Comment by mahalakshme** [comment] 2023-09-26 08:33
@AchalaBelokar whenever u can add the logs for these kind of crash issues, add them - we ll know the issue better

**Comment by AchalaBelokar** [comment] 2023-09-26 08:36
"Log error content:
TypeError: Cannot read property 'getLineage' of null

This error is located at:
in IndividualProfile"

**Comment by mahalakshme** [comment] 2023-09-26 08:37
looks like same error logs as of https://github.com/avniproject/avni-client/issues/1108 - might be duplicate - anyways need to be verified.

**Comment by himeshr** [comment] 2023-09-26 09:54
> looks like same error logs as of #1108 - might be duplicate - anyways need to be verified.

No, this is a different issue not related to avniproject/avni-server#1108

Rather, it might be caused due to newly introduced AddressLevel.calculateLineage() method in avni-server repo

**Comment by himeshr** [comment] 2023-09-26 13:15
### The cause of this issue is that:
1. "Student" SubjectType doesnot have "Should sync by location" enabled for it, but rather has the "Sync by Direct Assignment" enabled.
2. So during sync, Students assigned to a User will be synced regardless of whether the Student's address falls within the catchment.
3. And this results in addressLevel being null for such Student's
4. Later, when the user clicks on such a subject (Student whose address is not in User's catchment), app breaks with error "TypeError: Cannot read property 'getLineage' of null"


The fix for this, is to ensure that 
- org adminstrators only assign Subjects to a User who falls within their catchment  OR
- org adminstrators  enables "Should sync by location" flag for the SubjectType

**Comment by vinayvenu** [comment] 2023-09-27 03:18
@himeshr @mahalakshme lets discuss this during standup. 

There is no way for the person assigning to ever know that they cannot be assigned. This might need to be a rule we should enforce to prevent such errors. I am thinking of two things

**Comment by himeshr** [comment] 2023-09-27 05:29
After discussion, we'll do the following fix in Product.

During Subject assignment to a User:
 - Add check to ensure Subject lies within User's catchment
 - Add unit test for presence of GroupSubject and MemberSubjects within User's catchment

Additionally, we'll be making suitable modifications in Prod implementations, to enable "Sync By Location" where-ever its not enabled, as that's a primary requirement in current version of Avni-client.

**Comment by mahalakshme** [comment] 2023-09-28 05:41
@AchalaBelokar when the subject type has only "Direct Assignment" enabled, then when assignment is made, it should show error when an individual out of users catchment is assigned to the user. otherwise should work.

**Comment by himeshr** [comment] 2023-10-06 13:18
The check we have added, disallows sync of directly assignable "Member" subjectTypes that have different 
"Location type where this subject can be registered" in-comparison to their Group subjectTypes.
Ex: LAHI org, KarigarBatch(District) and Student(UDISE)..

### Fix:
~Check for "Member" subjectTypes address falling within the user's catchement, fetching seperately the Address levels for each subjectType~

We should not check for "Member" subjectTypes address is within the user's catchement.

### QA task:
The "Direct subject assignment to User" for a GroupSubject should work, even when the GroupSubject RegistrationLocationType is higher than MemberSubject RegistrationLocationType

**Comment by mahalakshme** [comment] 2023-10-18 09:50
We are not showing the error when the subject/group subject is assigned to an out of catchment user via checkbox selection and we are showing error only assigment done via Actions. This card released as part of 5.0.0 but we can fix this as part of 5.1.0

**Comment by himeshr** [comment] 2023-10-20 05:52
Attached screenshot of error being surfaced when subject/group subject is assigned to an out of catchment user via checkbox selection.

https://github.com/avniproject/avni-client/assets/72493481/9cedd851-7eb6-4e7e-b736-db9c61bbe74c

**Comment by ashusvnath** [comment] 2023-10-23 06:58
I've put a  comment on the code, but it is non-blocking, moving this story to qa ready.

**Closed as completed** 2023-10-26 05:10 UTC
Labels: bug
