### ISSUE TITLE
BugSnag Error - Item to delete is undefined in entityQueue

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-client#1027] opened 2023-06-16 04:28 UTC
**BugSnag Error**
https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-client/errors/64889a22d0d0370008e425d0

https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-client/errors/6482f2f0c3edf4000896c54a

**Management of BugSnag error and BugSnag**
https://avni.readme.io/docs/how-to-use-bugsnag

**Comment by vinayvenu** [comment] 2023-06-23 06:55
Duplicate of #843

**Closed as completed by vinayvenu** 2023-06-23 06:55 UTC
Labels: duplicate, bugsnag
