### ISSUE TITLE
BugSnag Error (Avni Client)

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-client#1019] opened 2023-06-14 04:42 UTC
**BugSnag Error**
https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-client/errors/6482f2f0c3edf4000896c54a?event_id

**Management of BugSnag error and BugSnag**
https://avni.readme.io/docs/how-to-use-bugsnag

**Comment by vinayvenu** [comment] 2023-06-23 06:55
Duplicate of #843 . Closing

**Closed as completed by vinayvenu** 2023-06-23 06:55 UTC
Labels: bugsnag
