### ISSUE TITLE
App is getting crashed with error Fatal error

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#1293] opened 2024-02-09 05:47 UTC
The app is getting crashed when we save the program ebility in lahi with error displayed as 
Fatal error : Exception in Host Function : Accessing object type EmbeddedKeyValue which has been invalidated or deleted 

env : prerelease
apk version or name : generic-prerelease-8f8a6b6e0b2c08ca78e4974579971383a134fb85.apk
username : dinesh@lahi

same issue happen for goonj as well 
user name : beulah@goonj

Steps to reproduce:
1. Login to lahi org
2. register the student
3. go to general encounter 
4. click on the program eligibility  check
5. flll the form and try to save it

Excepted result : app should save the ecounter
Actual result : app is getting crashed with fatal error 

https://github.com/avniproject/avni-client/assets/127730126/eab0db7e-5be3-4bb9-9f4f-e432b816dcfd

**Comment by himeshr** [comment] 2024-02-12 09:27
Unable to reproduce the issue, should have been fixed after code changes done for #1291 

https://github.com/avniproject/avni-client/assets/72493481/5c44e720-5a40-4410-8d1a-53e0c6b2fe7e

**Comment by himeshr** [comment] 2024-02-12 09:28
Duplicate of #1291

**Closed as completed by himeshr** 2024-02-12 09:28 UTC
Labels: bug
