### ISSUE TITLE
EnrolmentEligbiltyRule does not work in case of stitching

### ISSUE THREAD

**Issue by hithacker** [avniproject/avni-client#308] opened 2020-03-24 09:32 UTC
EnrolmentEligbiltyRule does not work when we do Register+Enrol directly from the home screen register button. It works fine when we just register the subject and then do enrolment from the subject dashboard.

I think it may not work also when there is a WorkListUpdation rule adding the enrolment item.

@nupoorkhandelwal had found this when testing enrolment eligibility rule. Divya from SoftCorner also found this recently while working on Setco.

**Comment by arjunk** [comment] 2020-04-13 07:57
EnrolmentEligibilityCheck rule is to hide enrolment options from subject dashboard. 
For Register+Enrol scenario, this is not a bug imo. this is a known behaviour. we cannot anticipate at the time user is triggering this action (register+enrol) as the subject is still not registered so we cannot hide that button.  the best way would be to put a validation check at enrolment save. thats how we have tackled in the past. 
the implementer can also take care of this in the worklistupdation rule by invoking the same logic. 
curious what is the behaviour folks are expecting

**Comment by vinayvenu** [comment] 2020-05-14 09:34
Added the detail in documentation (https://avni.readme.io/docs/writing-rules#enrolmenteligibilitycheck-rule). Closing this issue.

**Closed as completed by vinayvenu** 2020-05-14 09:34 UTC
Labels: bug
