### ISSUE TITLE
Sync does not work

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#911] opened 2023-03-24 11:57 UTC
### Details
Environment - prerelease
Login - taqi@ihmp
To reproduce - Login and sync. Sync shows error (see screenshot)

### Error
Sync completed dispatching reset
Notifying Bugsnag TypeError: Fatal error: undefined is not an object (evaluating 'n.privilegeEntity')
03-24 14:51:57.550 27389 27433 I ReactNativeJS: 'App', 'renderError', 'Fatal error: undefined is not an object (evaluating \'n.privilegeEntity\')\nStacktrace:[{"columnNumber":3261,"lineNumber":941,"functionName":"i","source":"i@index.android.bundle:941:3261","fileName":"index.android.bundle:941:3261"},{"columnNumber":4028,"lineNumber":941,"source":"index.android.bundle:941:4028","fileName":"index.android.bundle:941:4028"},{"columnNumber":29369,"lineNumber":449,"source":"index.android.bundle:449:29369","fileName":"index.android.bundle:449:29369"},{"columnNumber":20003,"lineNumber":449,"functionName":"uu","source":"uu@index.android.bundle:449:20003","fileName":"index.android.bundle:449:20003"},{"columnNumber":29174,"lineNumber":449,"source":"index.android.bundle:449:29174","fileName":"index.android.bundle:449:29174"},{"columnNumber":43597,"lineNumber":449,"functionName":"Ef","source":"Ef@index.android.bundle:449:43597","fileName":"index.android.bundle:449:43597"},{"columnNumber":3947,"lineNumber":941,"functionName":"value","source":"value@index.android.bundle:941:3947","fileName":"index.android.bundle:941:3947"},{"columnNumber":1739,"lineNumber":732,"functionName":"value","source":"value@index.android.bundle:732:1739","fileName":"index.android.bundle:732:1739"},{"columnNumber":2259,"lineNumber":732,"source":"index.android.bundle:732:2259","fileName":"index.android.bundle:732:2259"},{"columnNumber":1277,"lineNumber":76,"source":"index.android.bundle:76:1277","fileName":"index.android.bundle:76:1277"},{"columnNumber":528,"lineNumber":76,"functionName":"p","source":"p@index.android.bundle:76:528","fileName":"index.android.bundle:76:528"},{"columnNumber":2671,"lineNumber":76,"functionName":"callTimers","source":"callTimers@index.android.bundle:76:2671","fileName":"index.android.bundle:76:2671"},{"columnNumber":3580,"lineNumber":54,"functionName":"value","source":"value@index.android.bundle:54:3580","fileName":"index.android.bundle:54:3580"},{"columnNumber":759,"lineNumber":54,"source":"index.android.bundle:54:759","fileName":"index.android.bundle:54:759"},{"columnNumber":2583,"lineNumber":54,"functionName":"value","source":"value@index.android.bundle:54:2583","fileName":"index.android.bundle:54:2583"},{"columnNumber":731,"lineNumber":54,"functionName":"value","source":"value@index.android.bundle:54:731","fileName":"index.android.bundle:54:731"},{"functionName":"value","source":"value@[native code]","fileName":"[native code]:0:0"}]'

While try sync the app popup or shows the error (App will restart now Fatal error:undefined is not an object(evaluating'n.privilegeEntity,)
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/09a000bb-79cf-4e72-b296-324efbd7cdec)

**Comment by mahalakshme** [comment] 2023-03-28 12:16
Unable to reproduce the issue.

**Comment by Dinesh2019** [comment] 2023-03-29 04:49
Ignore this tested in wrong environment. 
We can able to reproduce the defect.
Steps to Reproduce;
1.Login to avni app.("prerelease apk is here - 
https://app.circleci.com/pipelines/github/avniproject/avni-client/1561/workflows/0e512aa0-fc9d-4a2a-b575-32f20b209b5b/jobs/9961/artifacts")
2.Automatically data got sync and it will show you a popup Sync Completed.
Screenshot below.
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/e601b781-d078-40e6-b228-a90acc604384)
3.After clicking Ok getting the below error.
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/145e6be6-befc-42be-8822-2bdf86b5fee8)

**Comment by sachsk** [comment] 2023-03-29 06:21
@Dinesh2019 this is not a product bug. It was an issue with privileges.

**Comment by vinayvenu** [comment] 2023-04-04 04:58
@sachsk  Javascript syntax errors most probably cannot be a data issue. Moving this to QA Failed. If you think this still should not be fixed, can you put the exact reason for failure?

**Comment by Dinesh2019** [comment] 2023-04-12 10:21
@sachsk Still we face the sync error
Steps to Reproduce;
1.Login to avni app.("prerelease apk is here -
https://app.circleci.com/pipelines/github/avniproject/avni-client/1561/workflows/0e512aa0-fc9d-4a2a-b575-32f20b209b5b/jobs/9961/artifacts")
2.Automatically data got sync and it will show you a popup Sync Completed.
Screenshot below.
env: pre-release
used id : taqi@ihmp
hence re-opening the ticket
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/fe4d59d8-f6bb-47de-952f-4bbac218160c)

**Closed as completed** 2023-04-12 14:19 UTC
Labels: bug
