### ISSUE TITLE
APFOdisha, DashboardCard, Bugsnag - Crashing

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-client#1086] opened 2023-08-30 11:42 UTC
https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-client/errors/64e08b0f91f5dd0008ba4a1b

TypeError Fatal error: null is not an object (evaluating 'this.gender.name') 
    /home/circleci/avni-client/packages/openchs-android/node_modules/openchs-models/dist/Individual.js:796:48 value
    /home/circleci/avni-client/packages/openchs-android/src/views/common/SubjectInfoCard.js:53:111 value
    /home/circleci/avni-client/packages/openchs-android/src/views/common/SubjectInfoCard.js:115:80 value
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:5037:21 finishClassComponent
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:6982:25 performUnitOfWork
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:6975:54 workLoopSync
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:6957:6 renderRootSync
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:6656:34 performSyncWorkOnRoot
    [native code] oi
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:2139:22 flushSyncCallbacks
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:8099:39 batchedUpdatesImpl
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1106:30 batchedUpdates
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1137:17 _receiveRootNodeIDEvent
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1209:30 receiveTouches
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:417:32 value
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:114:26 
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:368:8 value
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:113:17 value
    [native code] value

**Comment by vinayvenu** [comment] 2023-08-31 06:23
Caused by Individuals missing gender. This looks like a manual update. Closing and raising a ticket on implementations.

**Closed as completed by vinayvenu** 2023-08-31 06:23 UTC
