### ISSUE TITLE
Authenciation failed error is not showing with the invalid username and password

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#1169] opened 2023-11-03 09:43 UTC
When we login the client app with the invalid data app is not showing the error instead again coming back to home page with password already saved 

Steps to reproduce :

1.Open avni app 
2.enter the username : beulah@gvamp (incorrect username ) correct user is : beulah@gvamp_uat
3.enter the password : password 
4.App ask for slow performance click on that 
5.app again comes back to the login page

https://github.com/avniproject/avni-client/assets/127730126/20dadc89-8172-4118-8610-1871ec69781b

**Comment by vinayvenu** [comment] 2023-11-03 10:11
@Dinesh2019 the description of this issue is incorrect because the original username and password is correct, but there was a problem with the fast sync db. The app shows Authentication failure if it is actually incorrect.

**Comment by vinayvenu** [comment] 2023-11-03 10:13
Closing this issue - "Working as Designed".

**Closed as completed by vinayvenu** 2023-11-03 10:13 UTC
