### ISSUE TITLE
Search option is taking a more time and time consuming 

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1440] opened 2024-06-26 09:16 UTC
**Describe the bug**
Search option is taking a more time and time consuming 
I Login to himeshr@jsscp and try to serach a individual or pulwari.
but after clicking on search button it takes the 15 sec on 9.0
also I am trying to add child in phulwari it is taking a time.

**To Reproduce**
1. Login to himeshr@jsscp
2. click on search(search in mydashboard and search to add a member(here it crashes)) 
3. after that it will take a time

**Additional details**
- db uploaded
- some memory error can be seen in the logs 
- checked in different mobiles and doesn't seem to be a device specific issue

**Expected behavior**
result should be shown less than 15 sec
**Screenshots**

this recording is 8.0
https://github.com/avniproject/avni-client/assets/104890488/e6d6d5ee-0af2-481b-8402-2831830d92a8

this recording is on 9.0
https://drive.google.com/file/d/1ndbfsFBJ6k_2SBsVepZdJKuHVZIT-9Go/view?usp=drive_link
name with performance issue 1440

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by mahalakshme** [comment] 2024-06-26 11:18
@himeshr I ve added additional details in the card.

@vinayvenu the card was in 'New issues' since was waiting for some details from achala.

**Comment by himeshr** [comment] 2024-06-26 13:31
@AchalaBelokar Please confirm the following details..
I suspect that the 8.0 version is run using Production env apk, whereas 9.0 is run using Prerelease env apk.
Due to the difference in environments for jsscp org, there is difference in Search Result filters configured, as seen in below screenshot.
<img width="1702" alt="Screenshot 2024-06-26 at 6 59 04 PM" src="https://github.com/avniproject/avni-client/assets/72493481/20a0fac2-9a10-40fa-9b62-30bf411e59b8">

<img width="1691" alt="Screenshot 2024-06-26 at 6 58 03 PM" src="https://github.com/avniproject/avni-client/assets/72493481/f42cda57-b6d9-48bd-a1d9-c7e21576b8b5">


The cause for app to break in prerelease is not due to any code change, but due to the extra configuration of SearchFilter of type "Group Subject".

This is a problem that would not necessarily be a blocker for 9.0 release and might need more analysis on whether it can be fixed at all, due to the large volume of data that is present for that User's Catchment.

**Comment by mahalakshme** [comment] 2024-06-27 07:39
with less data not happening in 9.0. JSSCP permissions in prerelease is incorrect. So we might not have so much data in JSSCP. - need to check with big catchments like in CK and compare 8.1 and 9.0 to identify if performance has really degraded @AchalaBelokar

**Comment by mahalakshme** [comment] 2024-07-17 07:09
@AchalaBelokar  moving this to done since I guess u tested it

**Closed as completed** 2024-07-17 07:13 UTC
