### ISSUE TITLE
Not able to perform any actions after editing an unplanned visit.

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-client#1225] opened 2023-12-16 06:30 UTC
https://avni.freshdesk.com/a/tickets/3335

**Describe the bug**
The user after editing an unplanned encounter, the app doesn't allow the user to do anything else

**To Reproduce**
1. Login with a user
2. Find an individual that is enrolled in the child program and click on edit for an unplanned visit in the completed visits section.
3. Click on Next, Home etc..

**Expected behavior**
It doesn't allow you to do anything on the page, forcing the user to close the app.

**Screenshots**

https://github.com/avniproject/avni-client/assets/94247708/5cd2db71-2eda-4ffa-a72e-77da2c6c3474

Version- Latest from playstore(5.1.3)

**Comment by Gojo-Taqi** [comment] 2023-12-16 06:32
From the screencast, it's actually unclear, but I was trying to change an answer, click on Next, home, etc.

**Comment by vinayvenu** [comment] 2023-12-18 09:41
@Gojo-Taqi this is caused by an infinite loop in the rule. 

```
   do {
        earliestOffset++;
    } while (     
        !(moment(moment(childDOB).add(earliestOffset, 'month').toDate())
        .isAfter(programEncounter.earliestVisitDateTime, 'date'))  ||
        !(moment(moment(childDOB).add(earliestOffset, 'month').toDate())
        .isAfter(programEncounter.encounterDateTime, 'date'))  
        );
```

This gets into an infinite loop when earliestVisitDateTime is not there (when the visit is unscheduled). 

Closing this card assuming you can take care of things from here.

**Closed as completed by vinayvenu** 2023-12-18 09:41 UTC
