### ISSUE TITLE
[Performance] - Post release experience of avni-client 3.37.10

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-client#854] opened 2023-02-07 09:33 UTC
### Ashwini

Ashwini reports that there is not much benefit for them. The organisation is finding it hard to convince users to use the app. 

They have attached a video [here](https://avni.freshdesk.com/a/tickets/2379)
Workflow - Go from dashboard to list of cards to an individual, try to edit an encounter. 

### JSCS
Form data entry is slow. This makes data entry hard. This is similar to multiple "overlapping screens" thing that was reported otherwise

https://avni.freshdesk.com/a/tickets/2378

**Comment by petmongrels** [comment] 2023-02-08 09:52
Ashwini slowness issues
--------------
1. Opening overdue list. Reason - displaying too many subjects on the screen.
2. Opening a subject from the overdue list. Reason - it renders previous screen internally.
3. Pressing edit on encounter/enrolment.
    Reason a) same as 2
           b) display individual profile component multiple times
           c) due to display of radio/checkboxes
4. Pressing next
    Reason a) same as 2
           b) same as 3(b)
           c) same as 3(c)

JSCS slowness issues
-------------------
1. Opening of search screen
    Reason ? (not reproducible after batch 1 fix. probably fixed by it.)
2. Searching based on all fields (this search is slow in because of the numbers of records in the mobile database)
3. Edit registration details (due to the number of radio buttons)
4. Pressing next in registration (same as ashwini 4)


Fixes Batch 1
--------------
- 1 (reduced the number of subjects form 45 to 15)
- 2 (fixed the router to not rerender the previous screen)
- 3b (internally partitioned IndividualProfile into two semantic components to not do unnecessary dispatches)

    What to test
        - most important to test is to check whether screen navigation works properly. Check across the app with all regular screen flows.

Fixes Batch 2
--------------
- 3c (This should also fix issues related to my dashboard and search filters)

Cannot fix immediately
----------------------
- JSCS's issue of Search by All registration fields. There is a lot data on user's devices. This search goes across registration and enrolments. Upgrading realm version may fix this but it would take time.

**Comment by petmongrels** [comment] 2023-02-08 09:53
Will fix the batch 2 in #855

**Comment by mahalakshme** [comment] 2023-02-09 09:02
Testing:
Ashwini - Gudulur catchment:
Before fix
To render individial list 2 sec
2:12:45:588 - 2:12:47:892 - 2 sec 300ms
Going to a individual profile: 3 sec
2:15:18:462 - 2:15:21:109 - 3 sec 600 ms
Going to edit program enrolment - 3s
2:16:50:633- 2:16:53:187 - 3 sec, 400 ms
Edit of previous completed visit: 3s
2:18:42:927 - 2:18:45:469 - 3 sec 300 ms
Going to next: SRV: almost 4sec
2:19:29:831 - 2:19:32:658
Save: 2 sec
 
After fix:
To render individial list 1 sec - 50% improvement
1:16:53:332 - 1:16:54:366 - 1 sec 30 ms
Going to a individual profile: 2 sec - more than 50% improvement
1:18:14:809 - 1:18:16:195 - 1s 400ms
Going to edit program enrolment - 3s - less than 20% improvement
Not enough logs to measure
Edit of previous completed visit: 3s - less than 20% improvement
 Going to next: SRV: 2s - 50% improvement
Save: 2 sec
2:11:20:509 - 2:11:22:812 - 2 sec, 300ms

**Comment by mahalakshme** [comment] 2023-02-09 10:27
Edit of enrolment, encounter and registration details need to be tested as part of #855

**Closed as completed** 2023-02-14 03:39 UTC
Labels: bug
