### ISSUE TITLE
Different enties for different user groups

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#1093] opened 2023-09-08 14:20 UTC
In goonj we have the user group Everyone and All permission group 

User : AchalaB@gvamp_uat

In Everyone under permission we have the subject/Entity Type : Inventory Item 
Which as Entity type 

- View subject
- Approve subject
- Assign subject
- Void subject
- Register subject
- Edit subject

And for All permission group 
which as Entity type 

- Assign Subject
- View subject
- Register subject
- Edit subject
- Void subject
- Add member
- Edit member
- Remove member
- Approve Subject
- Reject Subject

which might cause the app crash according to my assumption.

Steps to reproduce :

step 1:
1.Login to app
2.Search for the distrubtion
3.Clikc on the edit distrubtion and go to the inventory page
4.Click on the search icon on the inventory page and click on submit the app gets crash

step 2:
1.Login to app
2.go to the search page
3.click on the inventory and click on the submit app gets crash

https://github.com/avniproject/avni-client/assets/127730126/1c6ffa53-305c-4813-8ec2-ee6a423a50f5

**Comment by vinayvenu** [comment] 2023-09-11 04:52
@Dinesh2019 can you specify exactly where the app crashes?

**Comment by Dinesh2019** [comment] 2023-09-11 05:12
@vinayvenu added the screenshot and step to reproduce in the comment section please refer to it

**Comment by mahalakshme** [comment] 2023-09-20 07:25
@Dinesh2019 the issue doesn't seem to be caused by the reason what you suspect. Does crashing of app still persist?

'Reject Subject' permission is removed. Add, Edit and Remove member permission will appear only for group or household subject type.

Closing this issue. Reopen it if the issue persist.

**Closed as completed by mahalakshme** 2023-09-20 07:25 UTC
Labels: bug, user reported
