### ISSUE TITLE
Previous encounters not showing when entering data for a new encounter

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#1098] opened 2023-09-17 17:18 UTC
Expand icon not visible.

**Comment by vinayvenu** [comment] 2023-09-18 04:45
@mahalakshme where is this happening? Is this required for release 5.1.0?

**Comment by vinayvenu** [comment] 2023-09-20 05:11
Duplicate of #1094

**Closed as completed by vinayvenu** 2023-09-20 05:11 UTC
