### ISSUE TITLE
Offline dashboard navigation is broken - [JNPCT]

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/avni-client#926] opened 2023-04-05 13:30 UTC
**Environment:**
https://prerelease.avniproject.org/
**Build version:**
1-a12db

**Organization:**
JNPCT

**User**
utkarshh@jnpct

**Steps to reproduce**
1. Login in the application.
2. Click on more, click on Offline dashboard.
3. For a second it displays the dashboard screen and then immediately gives "Fatal error : Unexpected token '.' "

**Expected outcome**
App should navigate user to the offline dashboard screen successfully.

Attaching screenshot:
![WhatsApp Image 2023-04-05 at 18.51.31.jpg](https://images.zenhubusercontent.com/61dbee9a6fc777578773b609/a7e6e64b-6ec1-4722-b397-0c6e0aa4680c)

**Comment by vinayvenu** [comment] 2023-04-06 05:12
@utkarshavni can you add details of environment, release and username so that it is easier to reproduce the bug?

**Comment by petmongrels** [comment] 2023-04-06 11:41
this is caused by a rule that looks like this.

'use strict';
({params, imports}) => {
    const isHighRisk = (enrolment) => {
        const obs = enrolment.findLatestObservationInEntireEnrolment('High Risk Conditions');
        return obs ? !_.isNull(obs) : false;
    };
    const deliveryAbortionCheck = (enrolment) => {
        const deliveryEnc = enrolment.getEncountersOfType('Delivery Form');
        const abortionEnc = enrolment.getEncountersOfType('Abortion Form');
        const deliveryEncSaheli = enrolment.getEncountersOfType('Delivery - Saheli');
        const abortionEncSaheli = enrolment.getEncountersOfType('Abortion - Saheli');
        const anc = enrolment.getEncountersOfType('ANC');

        return .isEmpty(deliveryEnc) && .isEmpty(abortionEnc) && .isEmpty(deliveryEncSaheli) && .isEmpty(abortionEncSaheli) && !_.isEmpty(anc);
    }
    return params.db.objects('Individual')
        .filter((individual) => individual.voided === false && _.some(individual.enrolments, enrolment => enrolment.program.name === 'Pregnancy' && enrolment.programExitDateTime == null && enrolment.voided === false && isHighRisk(enrolment) && deliveryAbortionCheck(enrolment)))

};

**Comment by petmongrels** [comment] 2023-04-06 11:42
Working on this card so that the user knows that this is a rule failure

**Comment by petmongrels** [comment] 2023-04-06 12:20
Created story for handling this.
No change done.

https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-client/928

**Comment by AchalaBelokar** [comment] 2023-04-07 08:32
- [ ] there was no change made by vivek so moving this card at it is

**Closed as completed** 2023-04-12 14:19 UTC
Labels: bug
