### ISSUE TITLE
Standard report card for Due is broken

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-client#813] opened 2023-01-23 08:52 UTC
Name of org :- sakhiapp
Version of the app :- 3.37.5-5....

Note :- Make sure you set the date to 16 Feb 2023.
Also the bug appears only for this one date (16 Feb). If the date is 15 or 17, it works fine.

When you open the app, there are a bunch of reports in the home screen that you can see.
On the top, there are two standard reports called **Due** and **Overdue**. 

On clicking Due, you can see the following image in the bottom
![Screenshot from 2023-01-23 14-07-42.png](https://images.zenhubusercontent.com/627c9e38b2b7107ec1888b53/f5f45c45-c8f4-4fcf-80e4-7a951b60c8cd)

And on clicking on the individual, you can see as shown in the picture below
![Screenshot from 2023-01-23 14-07-54.png](https://images.zenhubusercontent.com/627c9e38b2b7107ec1888b53/e4a9f3ab-56b7-4996-a4ce-2b44996ed8b3)

**Comment by vinayvenu** [comment] 2023-01-24 06:46
@Gojo-Taqi  This is expected behaviour. The visit was due on 14th and goes overdue after 16th. Due to this it will show up on the "Due" list. However, the visit is overdue as of "today", which is why it is showing up as overdue on the subject dashboard. 

Closing this card.

**Closed as completed by vinayvenu** 2023-01-24 06:46 UTC
