### ISSUE TITLE
Locations of different types at the same level not categorised by type

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/avni-client#1423] opened 2024-06-12 07:17 UTC
nupoork@adsr

### Issue:
- When there are multiple location types at same level, everything should display parallely like the below image. 

https://github.com/avniproject/avni-client/assets/10369963/3b812b6c-223d-4125-961c-4abd6e72216a

- We have broken it in 7.2 version. Currently it displays all locations of different location types in the same level together

https://github.com/avniproject/avni-client/assets/10369963/420773de-b142-431b-970e-4b5722e36992

- Could be this [commit](https://github.com/avniproject/avni-client/commit/3975c5e3ae1b9eec7c61cc4ecb3e18ff3a873988) thats the cause of the issue.

### AC:
- Make the grouping of location types to work as in 6.1 version
- Should work so in all places where address level displays - search, filter, concepts

**Comment by mahalakshme** [comment] 2024-06-12 08:46
I see sync is working as expected for multiple address levels : https://drive.google.com/file/d/1ZHq2_DniPxt1oFCJpmPJ6yTEUnt3QxlJ/view?usp=drive_link

Try to set the right time in emulator and then try to resync.

But i ll see if something need to fixed with filters for different location types, since its not categorised well in UI

**Comment by nupoorkhandelwal** [comment] 2024-06-12 08:57
@mahalakshme  it is clearly visible in the screen recording, other two lowest address levels (ie.Village & Boarding) are not available in the registration form!

**Comment by mahalakshme** [comment] 2024-06-12 10:00
@nupoorkhandelwal the issue is not sync. In older versions all addresses were displaying in respective location types. Now it is all displaying under school itself. 
old:
<img width="390" alt="Screenshot 2024-06-12 at 3 28 37 PM" src="https://github.com/avniproject/avni-client/assets/10369963/ac2ca4fc-4456-43d4-9727-549dfd16d747">

new:
<img width="446" alt="Screenshot 2024-06-12 at 3 30 02 PM" src="https://github.com/avniproject/avni-client/assets/10369963/00161273-6a1c-4fdf-b3da-8e07d9aabbe3">

will prioritise the issue.

**Comment by 1t5j0y** [comment] 2024-06-13 07:33
Include regression of #1302 in QA scope.

**Closed as completed** 2024-06-18 09:13 UTC
