### ISSUE TITLE
[avni-client] subject remains in the device even after the address of the subject has been updated (the new address is not in the current catchment)

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#804] opened 2023-01-12 12:26 UTC
https://avni.freshdesk.com/a/tickets/2352

As specified in this support ticket, when address of the individuals were updated via admin console, even though the individuals kept showing in the old user's catchment, ideally, whenever address is updated to an address outside the catchment, user should not be able to view it in his device.

**Comment by sachsk** [comment] 2023-02-16 11:19
This is not a bug, the feature is working fine.
To fix this issue we have to add the entry in subject migration.
we need the old address id so I have asked them to share it.

**Comment by vinayvenu** [comment] 2023-03-06 06:07
The feature works fine. Closing for now. Will reopen if another instance comes in.

**Closed as completed by vinayvenu** 2023-03-06 06:07 UTC
Labels: bug
