### ISSUE TITLE
[avni-client] app crashes when one clicks on camera icon for image datatype

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-client#518] opened 2021-09-20 16:20 UTC
**Describe the bug**
In STCATP implementation, under CTC Group Subject Type >> Encounter CPC Group Training >> Form element Group --Training Documents >> Upload first document, then upload/capture first image >> App crashes when one selects the camera icon on the second image upload!

**Expected behavior**
The form should not crash while one is uploading image type of concepts/obs.

**Comment by vindeolal** [comment] 2021-09-21 08:29
Bugs found: 
- For the video form element "durationLimitInSecs" is stored as a string from the admin app and the client expects a double value.
- Still not able to reproduce the Image/Camera bug.

**Comment by vindeolal** [comment] 2021-09-24 04:37
Moving this on hold as other bug is not reproducible and waiting for more inputs from the client.

**Comment by vindeolal** [comment] 2021-10-07 03:21
Have upgraded the camera library. There were many crash fixes done in the library. Test all the camera features that we support(photo and video).
Staging APK: https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-bd495-2021-10-07-09-03-19.apk

**Closed as completed** 2021-12-02 11:02 UTC
Labels: bug
