### ISSUE TITLE
Unable to login some organisation on staging as well as production env

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-client#1052] opened 2023-07-19 09:32 UTC
**Describe the bug**
Unable to login some organisation on staging as well as production env

07-19 14:42:09.333 12113 16209 D ReactNativeJS: [2:42:09:333] [SyncService][Debug] Creating entity create functions for [object Object]
07-19 14:42:09.353 12113 16209 D ReactNativeJS: [2:42:09:353] [BaseService][Debug] Dispatching action: "SyncTelemetryActions.ENTITY_PULL_COMPLETED"
07-19 14:42:09.417 12113 16209 D ReactNativeJS: [2:42:09:416] [H::AC][Debug] Dispatching action: "SYNC.ON_UPDATE"
07-19 14:42:09.480 12113 16209 D ReactNativeJS: [2:42:09:480] [H::AC][Debug] Dispatched action completed: "SYNC.ON_UPDATE"
07-19 14:42:09.483 12113 16209 D ReactNativeJS: [2:42:09:483] [Requests][Debug] GET: https://server.avniproject.org/task?lastModifiedDateTime=1900-01-01T00:00:00.000Z&now=2023-07-19T09:11:43.146Z&size=100&page=0
07-19 14:42:09.488 12113 16209 I ReactNativeJS: [2:42:09:488] [CognitoAuthService][Info] Found token
07-19 14:42:09.899 12113 16209 E ReactNativeJS: 'SyncComponent-Sync', 'undefined is not an object (evaluating \'k.isQuestionGroup\'), {"line":462,"column":3111,"sourceURL":"index.android.bundle"}', 'index.android.bundle:462:3111\nforEach@[native code]\nindex.android.bundle:462:2993\nforEach@[native code]\nvalue@index.android.bundle:462:2917\nvalue@index.android.bundle:462:2732\nvalue@index.android.bundle:562:3627\nindex.android.bundle:988:10025\nreduce@[native code]\nvalue@index.android.bundle:988:9967\nvalue@[native code]\np@index.android.bundle:989:2038\nindex.android.bundle:989:2346\nu@index.android.bundle:69:157\nindex.android.bundle:69:866\nindex.android.bundle:76:1692\np@index.android.bundle:76:528\nN@index.android.bundle:76:918\ncallReactNativeMicrotasks@index.android.bundle:76:3079\nvalue@index.android.bundle:54:2935\nindex.android.bundle:54:1045\nvalue@index.android.bundle:54:2583\nvalue@index.android.bundle:54:1004\nvalue@[native code]\nvalue@[native code]'
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: console.error: SyncComponent-Sync undefined is not an object (evaluating 'k.isQuestionGroup'), {"line":462,"column":3111,"sourceURL":"index.android.bundle"} index.android.bundle:462:3111
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: forEach@[native code]
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: index.android.bundle:462:2993
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: forEach@[native code]
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: value@index.android.bundle:462:2917
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: value@index.android.bundle:462:2732
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: value@index.android.bundle:562:3627
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: index.android.bundle:988:10025
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: reduce@[native code]
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: value@index.android.bundle:988:9967
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: value@[native code]
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: p@index.android.bundle:989:2038
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: index.android.bundle:989:2346
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: u@index.android.bundle:69:157
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: index.android.bundle:69:866
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: index.android.bundle:76:1692
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: p@index.android.bundle:76:528
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: N@index.android.bundle:76:918
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: callReactNativeMicrotasks@index.android.bundle:76:3079
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: value@index.android.bundle:54:2935
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: index.android.bundle:54:1045
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: value@index.android.bundle:54:2583
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: value@index.android.bundle:54:1004
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: value@[native code]
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: value@[native code], stack:
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: Error@-1
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: p@39:268
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: p@39:359
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: s@37:362
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: construct@-1
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: <unknown>@35:481
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: v@35:669
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: h@35:1807
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: value@446:4992
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: value@741:2453
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: value@-1
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: u@69:156
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: <unknown>@69:865
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: <unknown>@76:1691
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: p@76:527
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: N@76:917
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: callReactNativeMicrotasks@76:3078
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: value@54:2934
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: <unknown>@54:1044
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: value@54:2582
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: value@54:1003
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: value@-1
07-19 14:42:09.931 12113 16211 E unknown:ReactNative: value@-1
07-19 14:42:09.976 12113 16209 D ReactNativeJS: [2:42:09:975] [H::AC][Debug] Dispatching action: "SyncTelemetryActions.SYNC_FAILED"
07-19 14:42:10.086 12113 16209 D ReactNativeJS: [2:42:10:086] [H::AC][Debug] Dispatched action completed: "SyncTelemetryActions.SYNC_FAILED"
07-19 14:42:10.092 12113 16209 D ReactNativeJS: [2:42:10:091] [H::AC][Debug] Dispatching action: "SYNC.ON_ERROR"
07-19 14:42:10.107 12113 16211 I bugsnag-react-native: callReactNativeMicrotasks@index.android.bundle:76:3079
07-19 14:42:10.157 12113 16209 D ReactNativeJS: [2:42:10:156] [H::AC][Debug] Dispatched action completed: "SYNC.ON_ERROR"
07-19 14:42:10.159 12113 16209 W ReactNativeJS: registerHeadlessTask or registerCancellableHeadlessTask called multiple times for same key 'syncJob'
07-19 14:42:10.166 12113 16209 I ReactNativeJS: [2:42:10:166] [AvniBackgroundJob-SyncJobSchedule][Info] Successfully scheduled
07-19 14:42:10.300 12113 16209 I ReactNativeJS: [2:42:10:300] [Sync][Info] Starting SyncService
07-19 14:42:10.300 12113 16209 I ReactNativeJS: [2:42:10:300] [Sync][Info] Getting SyncService
07-19 14:42:10.300 12113 16209 I ReactNativeJS: [2:42:10:300] [Sync][Info] Getting connection info
07-19 14:42:10.301 12113 16209 I ReactNativeJS: [2:42:10:301] [Sync][Info] Calling syncService.sync
07-19 14:42:10.301 12113 16209 D ReactNativeJS: [2:42:10:301] [SyncService][Debug] sync
07-19 14:42:10.316 12113 16209 D ReactNativeJS: [2:42:10:316] [BaseService][Debug] Dispatching action: "SyncTelemetryActions.START_SYNC"
07-19 14:42:10.348 12113 16209 D ReactNativeJS: [2:42:10:348] [mediaUploadRequired][Debug] false
07-19 14:42:10.361 12113 16209 D ReactNativeJS: [2:42:10:361] [BaseService][Debug] Dispatching action: "SyncTelemetryActions.RECORD_PUSH_TODO_TELEMETRY"
07-19 14:42:10.383 12113 16209 D ReactNativeJS: [2:42:10:383] [Requests][Debug] POST: https://server.avniproject.org/syncTelemetry
07-19 14:42:10.384 12113 16209 I ReactNativeJS: [2:42:10:384] [CognitoAuthService][Info] Found token
07-19 14:42:10.560 12113 16209 D ReactNativeJS: [2:42:10:559] [BaseService][Debug] Dispatching action: "SyncTelemetryActions.ENTITY_PUSH_COMPLETED"
07-19 14:42:10.634 12113 16209 I ReactNativeJS: [2:42:10:634] [Sync][Info] 0.005
07-19 14:42:10.635 12113 16209 I ReactNativeJS: [2:42:10:635] [Sync][Info] 0.005
07-19 14:42:10.635 12113 16209 D ReactNativeJS: [2:42:10:635] [BaseService][Debug] Dispatching action: "SyncTelemetryActions.SYNC_COMPLETED"
07-19 14:42:10.715 12113 16209 D ReactNativeJS: [2:42:10:715] [Requests][Debug] POST: https://server.avniproject.org/syncTelemetry
07-19 14:42:10.717 12113 16209 I ReactNativeJS: [2:42:10:717] [CognitoAuthService][Info] Found token
07-19 14:42:10.865 12113 16209 I ReactNativeJS: [2:42:10:864] [Sync][Info] 0.01
07-19 14:42:10.867 12113 16209 I ReactNativeJS: [2:42:10:867] [Sync][Info] 1
07-19 14:42:10.874 12113 16209 D ReactNativeJS: [2:42:10:872] [BaseService][Debug] Deleting all data from RuleFailureTelemetry
07-19 14:42:10.887 12113 16209 I ReactNativeJS: [2:42:10:886] [Sync][Info] Sync completed
07-19 14:42:34.848 12113 16209 I ReactNativeJNI: Memory warning (pressure level: TRIM_MEMORY_UI_HIDDEN) received by JS VM, ignoring because it's non-severe
07-19 14:43:58.707 12113 16209 D ReactNativeJS: [2:43:58:706] [y::AC][Debug] Dispatching action: "LVA.ON_MENU_CLICK"
07-19 14:43:58.708 12113 16209 D ReactNativeJS: [2:43:58:708] [y::AC][Debug] Dispatched action completed: "LVA.ON_MENU_CLICK"
07-19 14:43:58.709 12113 16209 D ReactNativeJS: [2:43:58:708] [LandingView][Debug] render
07-19 14:43:58.730 12113 16209 D ReactNativeJS: [2:43:58:729] [b::AC][Debug] Dispatching action: "Menu.ON_LOAD"
07-19 14:43:58.756 12113 16209 D ReactNativeJS: [2:43:58:756] [b::AC][Debug] Dispatched action completed: "Menu.ON_LOAD"
07-19 14:43:58.758 12113 16209 D ReactNativeJS: [2:43:58:758] [MenuView][Debug] render
07-19 14:44:09.744 12113 16209 D ReactNativeJS: [2:44:09:744] [TypedTransition][Debug] Route size: 1
07-19 14:44:09.746 12113 16209 D ReactNativeJS: [2:44:09:745] [Router][Debug] renderScene: Curr

**To Reproduce**
1. Go to 'client'
2. Login as AchalaB@poweruat, AchalaB@synctest
3. enter the password of that particular user
5. See error

**Expected behavior**
User should able to login for particular organisation 

**Screenshots**
<img width="327" alt="Screenshot 2023-07-19 at 2 38 12 PM" src="https://github.com/avniproject/avni-client/assets/104890488/97ac83a1-4ebd-414d-8423-f3acac480341">

**Comment by vinayvenu** [comment] 2023-07-19 09:34
@AchalaBelokar please do confirm if this is happening on the current master branch (4.0.0)
@vinayvenu Morning I found this issue on master. but now I am not able to reproduce

**Comment by himeshr** [comment] 2023-07-20 05:54
The "poweruat" org to which "AchalaB@poweruat" is linked to is invalidated and should not be used. It doesnot have any concepts, so during sync of task, we get into error while attempting to map concept values.

**Comment by himeshr** [comment] 2023-07-20 05:58
Unable to reproduce this issue for user AchalaB@synctest on Staging env, closing this for now.

**Closed as completed by himeshr** 2023-07-20 05:58 UTC
Labels: bug
